CC = gcc
CFLAGS = -Wall -std=c17

all: exercice1 exercice2 exercice3

exercice1: exercice1.c	
	$(CC) exercice1.c -o exercice1 $(CFLAGS)

exercice2: exercice2.c	
	$(CC) exercice2.c -o exercice2 $(CFLAGS)

exercice3: exercice3.c	
	$(CC) exercice3.c -o exercice3 $(CFLAGS)

clean:
	rm -f exercice1
	rm -f exercice2
	rm -f exercice3